---
- name: Crea una instancia y cloudwatch
  gather_facts: false
  hosts: all
  tasks:
        - name: Crea instancias y activa monitoreo
          ec2:
            key_name: awx
            group: databases
            instance_type: t2.micro
            image: ami-0f9932d25a05f910f
            wait: yes
            wait_timeout: 500
            count: 2
            instance_tags:
               Name: Altan_bdl_Dev_test_0
            monitoring: yes
            vpc_subnet_id: subnet-016ecfe6469c7e7e4
            assign_public_ip: yes
        - name: Muestra informacion
          debug:
            msg: "Instance name: {{ ansible_hostname }}"
